Task 2 dwh
MariDzin/Mariam_Dzindzibadze_WCASP24 pull request #10
Opened 2024-07-06 20:14 UTC by MariDzin

2024-07-10 09:33 UTC, marimldvnv requested changes
Hello Mariam, please see comments

2024-07-10 09:33 UTC, marimldvnv commented on DWH/task2/Introduction to Data Warehousing and ETL.homework2_task1.docx
There is no such dimension for star:
![image](https://github.com/MariDzin/Mariam_Dzindzibadze_WCASP24/assets/22323681/c13bdc6c-d04d-4bce-b80d-13597fb326e5)
star diagram is correct, just incorrect description.

snowflake schema is incorrect. it should not be similar to 3nf. it should be retrieved from star schema by normalizing a few dimensions. 
That is how snowflake schema looks like 
![image](https://github.com/MariDzin/Mariam_Dzindzibadze_WCASP24/assets/22323681/edfcef31-ec8f-434b-9c6d-387db1ae7e13)

also please provide diagrams as separate files too

2024-07-10 09:33 UTC, marimldvnv commented on DWH/task2/Introduction_to_DWH_and_ETL_Business_Template_TASK_2_2.docx
Not really clear for me the choice of address dimension in your case.
first of all, there should not be two of them. data is loaded from all the source systems to the same table.
secondly, is it an address of who/what? not clear reference to it from sale (looks like it is the location of a sale, but sounds bit illogical)
if address is about customer, that info should be in customer.

When you update model according recommendations, please think how to retrieve 5 dimensions (you may introduce something like payment method, or employee, or delivery method and etc.)

Price per item is rather about product, not the fact (for fact you have sales amount).
![image](https://github.com/MariDzin/Mariam_Dzindzibadze_WCASP24/assets/22323681/fb4ccdd0-7117-4a07-bf2a-bc1e5c91e7c8)

also please remove fact table from list of dimensions, it is a bit confusing.

as for the grain, please describe it from business perspective too

2024-07-10 15:58 UTC, MariDzin commented
> Hello Mariam, please see comments

i was not able to receive notifications from git, but I am all in now

2024-07-12 07:41 UTC, marimldvnv requested changes
Hello, please see comments

2024-07-12 07:41 UTC, marimldvnv commented on DWH/task2/Introduction_to_DWH_and_ETL_Business_Template_TASK_2_2.docx
let's think of status here. do you expect to update fact table rows in order to change the status constantly?
![image](https://github.com/user-attachments/assets/5ee6ad4f-1a9a-4356-9ce1-bfaaf08b8535)
in most cases fact table used only for insertions, it is not really convenient to update each row constantly to get last status. I would say that for such cases exists other structure of fact table (example)
![image](https://github.com/user-attachments/assets/7d5d4015-5f7c-4e61-9eb2-4e5d4267cee2)

so if you don't want to introduce such complex solution better go get rid of such columns in your table, which potentially should be updated

Dealsize in fact table- shouldn't it be replaced with dealsize_id which you introduced?

Please extend time dimension with some week number (will you have time cardinality or date cardinality? I would say date would be more efficient)

2024-07-12 15:50 UTC, marimldvnv approved these changes

2024-07-12 15:55 UTC, merged