upload file
MariDzin/Mariam_Dzindzibadze_WCASP24 pull request #13
Opened 2024-07-16 22:10 UTC by MariDzin

2024-07-16 22:10 UTC, MariDzin commented
i have a lot of errors for the sql code that i am trying to fix for about few hours already, as soon as i fix ill upload it too

2024-07-16 22:28 UTC, MariDzin commented
![image](https://github.com/user-attachments/assets/cf72dff0-e485-4cae-ac46-d48df57b8307)
i try to fix that error

2024-07-17 08:46 UTC, marimldvnv requested changes
Please see comments. 
Were you able to fix the issue with accessing the file?

2024-07-17 08:46 UTC, marimldvnv commented on DWH/Task5/Script-3.sql
All attributes of all tables in source layer should have VARCHAR datatype (we must retrieve data from source as it is and if we use some predefined datatype data may be corrupted when casting).
Please use commit after each dml operation.

2024-07-19 16:14 UTC, marimldvnv requested changes

2024-07-19 16:14 UTC, marimldvnv commented on DWH/Task5/Script-3.sql
...of ALL tables. in external too :) precision is up to you, but usually it is max = 255

2024-07-21 09:18 UTC, marimldvnv requested changes
Can you please provide your current versions of datasets? your code is not working for me
![image](https://github.com/user-attachments/assets/7f65f2fd-039e-4e66-9990-a34fc40523bc)

2024-07-22 20:54 UTC, MariDzin commented
HI, i provided updated databases in the pull request called- update databases

2024-07-23 10:13 UTC, marimldvnv approved these changes

2024-07-23 10:28 UTC, merged