Task 6 dwh
MariDzin/Mariam_Dzindzibadze_WCASP24 pull request #15
Opened 2024-07-18 18:59 UTC by MariDzin

2024-07-20 09:16 UTC, marimldvnv requested changes
Hello, please check your code, rework all mentioned issues and then I will b able to proceed. For now I can't check it fully because it is not working.

Also please fix older pull requests. staging area load also doesn't work

2024-07-20 09:16 UTC, marimldvnv commented on DWH/Task6/tables.sql
![image](https://github.com/user-attachments/assets/72c354fb-832a-4e74-8ace-80c0bd395f66)
update dt is not needed for scd type 2 tables.

order of tables creation is not correct - run fails because of references to not existing tables.

2024-07-20 09:16 UTC, marimldvnv commented on DWH/Task6/defaul_Values.sql
did you try to run your scripts? please check them before committing
![image](https://github.com/user-attachments/assets/95be5be0-e894-4c54-a290-cbb8057939a0)
![image](https://github.com/user-attachments/assets/11b680e5-6b1f-44df-8646-07c0a09d8d2e)
![image](https://github.com/user-attachments/assets/416af5db-5fdc-4496-ace8-b7e7b3bb2434)
![image](https://github.com/user-attachments/assets/3f041be7-c14d-4fb6-87d9-b0db381049f4)
![image](https://github.com/user-attachments/assets/fe94a1f5-482a-4619-9013-5bfc17fe4b78)
![image](https://github.com/user-attachments/assets/280701fa-6d21-44c9-95a3-8347f546c108)
![image](https://github.com/user-attachments/assets/2b7b3965-c72f-49a7-adba-c8711e1f2a29)

2024-07-20 09:16 UTC, marimldvnv commented on DWH/Task6/extraction.sql
source table should be src table, not external (check the whole code)
![image](https://github.com/user-attachments/assets/ac7398aa-c695-41e2-8088-1d719cb30678)
![image](https://github.com/user-attachments/assets/51fab1a6-b54f-49d0-b991-8f201176ac19)


please do not add such scripts into committed task, better just to update table creation script.
![image](https://github.com/user-attachments/assets/17f52ad1-d297-4f8c-a374-3ac5ca8cb317)

do not use default constraints, NULLs handling should be done in DML
![image](https://github.com/user-attachments/assets/fb312574-682d-4364-aade-c0978ddb8313)

when you inserting data into tables with FKs you should not use names in ON condition. This is one of the reasons why you have source triplet, so use it.
![image](https://github.com/user-attachments/assets/197e9b2c-067b-473d-9d89-566439a88f4f)


definitely not:
![image](https://github.com/user-attachments/assets/67d2003c-2593-4b0f-aa45-da6494db07a2)
if you wanted to receive state_id from 3nf table, you need to do the same as for the first CTE (of course with proper join condition)

where did it come from?
![image](https://github.com/user-attachments/assets/4e4dc7e5-f11d-428c-95e3-e3f7dc3b5f97)

2024-07-20 14:10 UTC, MariDzin commented on DWH/Task6/defaul_Values.sql
i did run the code and it was working with me. ill go through them all  again and correct the issues

2024-07-20 15:09 UTC, MariDzin commented on DWH/Task6/defaul_Values.sql
i got why there was error, because order of tables for insert was not right, i corrected it, should not be the problem anymore

2024-07-21 09:55 UTC, marimldvnv requested changes

2024-07-21 09:55 UTC, marimldvnv commented on DWH/Task6/tables.sql
![image](https://github.com/user-attachments/assets/fe3f70ee-9c25-43a8-ad89-c10411efbaef)

constraints to SCD2 tables are prohibited

also I don't think that unique constraints are relevant as they are now. We may have same values coming from different sources - such constraints will not allow to insert data to table

2024-07-21 09:55 UTC, marimldvnv commented on DWH/Task6/extraction.sql
why do you use coalesce for natural keys? they should not be NULL, otherwise there just will be no data in source.

I see only one source. also no handling of null value if country does not exist
![image](https://github.com/user-attachments/assets/dc94798e-00a7-4837-abd1-a502c34b3017)

why no state and join?
![image](https://github.com/user-attachments/assets/7289b1dd-510d-4acc-874d-5125d0440d0f)
also ON condition is not fixed.

source triplet is not used again
![image](https://github.com/user-attachments/assets/3034bb54-0792-4da3-95da-54489272e462)

you are trying to update data for customer, am I right that it is for scd2? then what about new version of row and closing of the old one? If you are skipping that part for now then there should be not update but only insert (as for other tables)
![image](https://github.com/user-attachments/assets/e1a08ea2-3643-467c-9768-7fa4ab32d784)


no source triplets again
![image](https://github.com/user-attachments/assets/a526d29e-3094-4703-b444-2a971d36b243)

2024-07-25 16:04 UTC, merged